select * from customer;

use customer_behavior_analysis;

-- Q1 what is the total revenue generated by male vs female customers-- 

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2 which customer used a discount but stil spent more than the average purchase amount?

select ï»¿Customer_ID, purchase_amount
from customer
where Discount_Applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3 which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 compare the average purchase amount between standard and express shipping?

select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('Standard', 'Express');

-- Q5 do subscribed customer spent more? compare average spend and total revenue between subscriber and non-subscriber?
select subscription_status, count(custoner_id) as total_customer,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6 Which 5 product have the highest percentage of purchase with discount applied? 
select item_purchase,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 segment customer into new, returning, and loyal based on there total no. of previous purchase, and shipping?
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment;
    
-- Q8 what are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9 are customer who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
